version: "3"
services:
  node-app:
    build:
      context: .
      target: development
      # args:
      #   - NODE_ENV=development
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
    
